apiVersion: v1
kind: Service
metadata:
  name: e2esa-webapp01-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: e2esa-webapp01
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
   tire: front-end
   env: dev
   app: e2esa-webapp01
