# ClusterRoleBinding binds Clusterrole with Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: e2esa-service-account-01
  name: e2esa-service-account-01
  namespace: e2esa-ns-01
